name: Licensed CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v4
        with:
          cache: npm
          node-version: 20

      - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          ruby-version: ruby
          bundler-cache: true

      - uses: github/setup-licensed@be11bcbb82e3140b6cf260e647c3efeeca8fcefd # v1
        with:
          version: "4.x"

      - run: npm install

      - run: npm run test

      - name: Run licensed-ci
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: push
